name: Delete Last Commit on Build Failure

on:
  workflow_run:
    workflows: ["Deploy Hugo site to Pages"]
    types:
      - completed

jobs:
  delete_last_commit_on_failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.name == 'Deploy Hugo site to Pages' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 2

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Delete last commit and force push
        run: |
          git reset --hard HEAD~1
          git push origin HEAD --force 
